-- Migration: Add species_comments table
-- Run this in Supabase SQL Editor if your database was created before comments were added.
-- After running, execute `npm run types` to regenerate lib/schema.ts.

create table if not exists species_comments (
  id int generated by default as identity primary key,
  species_id int not null references species on delete cascade,
  author uuid not null references profiles,
  content text not null,
  created_at timestamptz not null default now()
);

alter table species_comments enable row level security;

drop policy if exists "Comments are viewable by everyone." on species_comments;
create policy "Comments are viewable by everyone." on species_comments
  for select using (true);

drop policy if exists "Users can insert their own comments." on species_comments;
create policy "Users can insert their own comments." on species_comments
  for insert with check (auth.uid() = author);

drop policy if exists "Users can delete their own comments." on species_comments;
create policy "Users can delete their own comments." on species_comments
  for delete using (auth.uid() = author);
